# Generated by Django 4.0.3 on 2022-04-01 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=128)),
                ('graphic', models.ImageField(upload_to='')),
                ('graphic_last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAdmins',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AB_tests.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('start_group_a_date', models.DateTimeField()),
                ('start_group_b_date', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('result', models.FloatField(null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AB_tests.site')),
            ],
        ),
    ]
