# Generated by Django 4.0.3 on 2022-04-04 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AB_tests', '0002_site_users_delete_siteadmins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='users',
            field=models.ManyToManyField(related_name='sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
