# Generated by Django 4.0.3 on 2022-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AB_tests', '0003_alter_site_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtest',
            name='start_group_a_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='abtest',
            name='start_group_b_date',
            field=models.DateField(),
        ),
    ]
