# Generated by Django 4.0.3 on 2022-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AB_tests', '0004_alter_abtest_start_group_a_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abtest',
            old_name='start_group_a_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='abtest',
            name='start_group_b_date',
        ),
        migrations.AddField(
            model_name='abtest',
            name='url_control_group',
            field=models.CharField(default=-2022, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abtest',
            name='url_test_group',
            field=models.CharField(default=-2022, max_length=128),
            preserve_default=False,
        ),
    ]
