# Generated by Django 4.0.3 on 2022-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AB_tests', '0005_rename_start_group_a_date_abtest_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abtest',
            name='url_control_group',
        ),
        migrations.RemoveField(
            model_name='abtest',
            name='url_test_group',
        ),
        migrations.AddField(
            model_name='abtest',
            name='urls_control_group',
            field=models.TextField(default='01/01/2022'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abtest',
            name='urls_test_group',
            field=models.TextField(default='01/01/2022'),
            preserve_default=False,
        ),
    ]
